config/routes.rb
Turnthetide::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resource :feeds
  resource :users, only: [:show]

  root to: 'pages#home'

  match '/index',          to: 'feeds#index'
  
  match '/about',          to: 'pages#about'
  match '/faq',            to: 'pages#faq'
  match '/contact',        to: 'pages#contact'
  match '/tutorial',       to: 'pages#tutorial'
  match '/levels',         to: 'pages#levels'

  match '/linechart',         to: 'visualizations#linechart'
  match '/piechart',          to: 'visualizations#piechart'

end

app/views/layouts/_footer.html.erb
     <!-- FOOTER -->
     <!--<div style="padding-top:50px"></div> -->
      <footer>
        <p class="pull-right" style="margin-right:50px;"><a href="#">Back to top</a></p>
        <p style="margin-left:50px;">© 2014 Turn The Tide · <%= link_to "Contact", contact_path %>
      </footer>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
      <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
      <div class="container">
        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/">Turn the Tide</a>
            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li><a href="/">Home</a></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "How To", tutorial_path %></li>
                <% if user_signed_in? %>
                  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Log In", new_user_session_path %></li>
                  <li><%= link_to "Register", new_user_registration_path %></li>
                <% end %>
            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->
      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turn the Tide</title>
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,400' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "highcharts" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <%= render 'layouts/header' %>
  <!--<#% flash.each do |name, msg| %>
    <#%= content_tag :section, msg, :id => "flash_#{name}", :class => "flash alert" %>
  <#% end %>-->
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>